#RequireAdmin
Run(@ScriptDir & '\autocom_release_full.exe')
AutoItSetOption('MouseCoordMode', 0)

WinWait('Select Setup Install Mode')
WinActivate('Select Setup Install Mode')
MouseClick('primary', 91, 145, 1, 0)
WinWait('Setup - Autocom version 2020.23')
WinActivate('Setup - Autocom version 2020.23')
MouseClick('primary', 54, 379, 1, 0)
Send("{ENTER}")
ControlSetText('Setup - Autocom version 2020.23', '', '[CLASS:TPasswordEdit]', 'ThankYou')
Sleep(2000)
Send("{ENTER}")
Send("{ENTER}")
Send("{ENTER}")
Send("{ENTER}")
WinWait('Microsoft Visual C++ 2010  x86 Redistributable Setup')
WinActivate('Microsoft Visual C++ 2010  x86 Redistributable Setup')
MouseClick('primary', 54, 267, 1, 0)
Sleep(2000)
Send("{ENTER}")
Sleep(5000)
MouseClick("primary", 448, 446, 1, 0)
;correct-------------/////////
WinWait('Microsoft SQL Server Compact 4.0 x64 ENU')
WinActivate('Microsoft SQL Server Compact 4.0 x64 ENU')
Sleep(2000)
Send("{ENTER}")
Sleep(2000)
ControlClick('Microsoft SQL Server Compact 4.0 x64 ENU', '', '[CLASS:Button; INSTANCE:3]')
ControlClick('Microsoft SQL Server Compact 4.0 x64 ENU', '', '[CLASS:Button; TEXT:Install]')
Sleep(2000)
Send("{ENTER}")
Sleep(5000)
Send("{ENTER}")
Sleep(9000)
Send("{ENTER}")
WinWait('Microsoft .NET Framework 4.5.1')
WinActivate('Microsoft .NET Framework 4.5.1')
MouseClick('primary', 463, 444, 1, 0)
WinWait('Device Driver Installation Wizard')
WinActivate('Device Driver Installation Wizard')
Send("{ENTER}")
Sleep(5000)
Send("{ENTER}")
WinWait('Setup - Autocom version 2020.23')
WinActivate('Setup - Autocom version 2020.23')
Sleep(2000)
Send("{ENTER}")
Sleep(2000)
Run(@ScriptDir & '\AC 2020.23 Keygen setup final')
AutoItSetOption('MouseCoordMode', 0)

WinWait('Select Setup Language')
WinActivate('Select Setup Language')
MouseClick('primary', 229, 148, 1, 0)
WinWait('Setup - AC 2020.23 version 2.0')
WinActivate('Setup - AC 2020.23 version 2.0')
ControlSetText('Setup - AC 2020.23 version 2.0', '', '[CLASS:TPasswordEdit]', 'ROD-&-LOKI')
Sleep(2000)
Send("{ENTER}")
WinActivate('Setup - AC 2020.23 version 2.0')
Send("{ENTER}")
WinActivate('Setup - AC 2020.23 version 2.0')
Send("{ENTER}")
Sleep(10000)
WinActivate('Setup - AC 2020.23 version 2.0')
Send("{ENTER}")
WinActivate('Setup - AC 2020.23 version 2.0')
Send("{ENTER}")